apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${metallbip}
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system